# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36c238785822f277a37eaafc0a0521aad51f210d85029f471ec48cbaf68f55bb0ba68894d49a0ca01caba9243db8892a4bc1eb1bf8d8472a9addea8a3e417779
  GOOGLE_MAPS_API_KEY: AIzaSyALdNOnbFdZAlxNZ2hMQ6A-Ai3ia7aBpAk

test:
  secret_key_base: a08fffa538e423a8ebc2b17b5c53e5bdddd5339ad333a17fb86b8a5247a75c3c843aba8f0926ed46f9e5f7146b1a8bc6e13c3f4080b2695405abe4f9c0980a93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
